export const dashboardStats = [
  { label: "Applications Tracked", value: "84", subtext: "+7 this week" },
  { label: "Response Rate", value: "27.4%", subtext: "23 responses from 84 applications" },
  { label: "Interview Requests", value: "6", subtext: "7.1% conversion rate" },
  { label: "Needs Action", value: "4", subtext: "2 replies, 1 assessment, 1 review" },
];

export const mockApplications = [
  {
    id: "app_stripe",
    company: "Stripe",
    role: "Frontend Developer",
    status: "interview_requested",
    lastContact: "Today",
    nextAction: "Reply with availability",
    source: "LinkedIn",
    fitScore: 82,
    payListed: false,
  },
  {
    id: "app_vercel",
    company: "Vercel",
    role: "Web Engineer",
    status: "rejected",
    lastContact: "Yesterday",
    nextAction: "None",
    source: "Company Site",
    fitScore: 79,
    payListed: true,
  },
  {
    id: "app_acme",
    company: "Acme AI",
    role: "React Developer",
    status: "assessment_requested",
    lastContact: "2 days ago",
    nextAction: "Complete challenge",
    source: "LinkedIn",
    fitScore: 88,
    payListed: false,
  },
  {
    id: "app_linear",
    company: "Linear",
    role: "Product Engineer",
    status: "manual_review",
    lastContact: "2 days ago",
    nextAction: "Confirm classification",
    source: "Referral",
    fitScore: 73,
    payListed: true,
  },
  {
    id: "app_notion",
    company: "Notion",
    role: "Frontend Engineer",
    status: "application_confirmed",
    lastContact: "5 days ago",
    nextAction: "Wait",
    source: "LinkedIn",
    fitScore: 77,
    payListed: true,
  },
];

export const mockEmailSignals = [
  {
    id: "email_1",
    company: "Stripe",
    role: "Frontend Developer",
    sender: "jane@stripe.com",
    subject: "Next steps for Frontend Developer role",
    classification: "interview_request",
    confidence: 94,
    received: "Today",
    action: "Reply",
    reason: "The recruiter asks for availability for a first-round screen.",
    snippet: "Thanks for your application. We'd like to schedule a quick call next week.",
  },
  {
    id: "email_2",
    company: "Vercel",
    role: "Web Engineer",
    sender: "careers@vercel.com",
    subject: "Update on your application",
    classification: "rejection",
    confidence: 91,
    received: "Yesterday",
    action: "Confirm + Archive",
    reason: "The message says the team is moving forward with other candidates.",
    snippet: "After careful review, we will not be moving forward at this time.",
  },
  {
    id: "email_3",
    company: "Acme AI",
    role: "React Developer",
    sender: "talent@acme.ai",
    subject: "Coding assessment invitation",
    classification: "assessment_request",
    confidence: 88,
    received: "2 days ago",
    action: "Complete",
    reason: "The email includes a coding challenge link and deadline.",
    snippet: "Please complete the React assessment within the next 72 hours.",
  },
];
